### ISSUE TITLE
Add deployment instructions

### ISSUE THREAD

**Issue by imawhale** [StefMa/hugo-fresh#102]

**Comment by najamsk** [comment]
yes please i am banging my head to deploy this

**Comment by StefMa** [comment]
What are you searching for exactly?
The documentation is linked in the Readme. Somewhere in a sub page
everything is explained. Is there something I can improve?

**Comment by najamsk** [comment]
@StefMa I could be a blind but i couldn't find how to deploy it on netlify or vercel. Please do share the links If I missed them. I checked several times and failed to find anything from readme.

**Comment by StefMa** [comment]
💡 Got it. Thought there was a misspelling with the word "deployment". Thought it was more like "how to use the theme" ☺.

Yes, this isn't included in the docs. I also don't want to add it as this has nothing to do with the theme itself.

Anyways. This is how to deploy to vercel:
After you added the theme like I described [here](https://stefma.github.io/hugo-fresh/getstarted/) (without `hugo Server`), run
```
hugo --base-URL yourVercelSubDomain.vercel.app
```
The output is available in the public directory.
Go into it and run
```
vercel 
```
That's it 🙃

Hope that helped.

**Comment by najamsk** [comment]
Basically wanted to integrate forestry.io that proved web interface to add your posts and pages for hugo. Whenever you make change it pushed changes to your github. Now netlify or vercel ideally pick up those change build the site again and deploy it automatically.

I got this working with 2 attemps but cant make it work with vercel since fresh theme has go.mod at root and vercel cry that golang is not installed. 

Your instructions are good for theme if you are publishing it in public folder. The setup I was trying to figure out is for a client who wants some web interface to create cms like experience.
