### ISSUE TITLE
Allow theme to be used as a Hugo module

### ISSUE THREAD

**Issue by ringods** [StefMa/hugo-fresh#113]
Hugo 0.56 introduced [modules](https://gohugo.io/news/0.56.0-relnotes/) support. Themes can also be treated as a module now rather than adding them as a Git submodule. For this to work, one needs to add two files:

- `config.yml` (or .toml/.json)
- `go.mod`

[This fork](https://github.com/bep/hugo-fresh) shows this theme converted as a Hugo module. Can you integrate the above 2 files from the fork in this repo?

**Comment by StefMa** [comment]
Hi @ringods!

Thanks for the request.
I looked into this and it turned out that there is no need to change the existing implementation to support modules.
I'm not sure if that changed meanwhile, but with hugo 0.80.0 (current version), it is possible to use this theme as a module without any changes:

I testet it with a new hugo site and replaced the implementation for the current [exampleSite/config.yml](https://github.com/StefMa/hugo-fresh/blob/bd7401ae8cacaf567761d955d8c5516ebc4dceb7/exampleSite/config.yaml) with the following
```diff
- theme: hugo-fresh
+ module:
+  imports:
+    path: github.com/stefma/hugo-fresh
```
Then you have to run `go mod init YOUR_MODULE_NAME`.
That's it.

Does this help?

**Comment by StefMa** [comment]
I added a "how to use this theme with go modules" to the readme.
Checkout the [commit](https://github.com/StefMa/hugo-fresh/commit/cc31e5c6078f07cbb4608530d73c187dd76002ad) .
