### ISSUE TITLE
Question: Regarding setup the contact in section5

### ISSUE THREAD

**Issue by Informaticore** [StefMa/hugo-fresh#143]
How can I setup the contact form so I do get the mails? There is no documentation about it, it only says enable: true or false

**Comment by seapotter** [comment]
Ran into the same issue, and was a little confused as to why the contact form did nothing. Its because the form in https://github.com/StefMa/hugo-fresh/blob/master/layouts/partials/section5.html#L12 is not wired to have an action.

If you know much about form elements this is easy to fix. But if you are just trying to get something working you can:

* Create a form with [Formspree.io](https://formspree.io) or similar form creation service. 
* Modify the code in https://github.com/StefMa/hugo-fresh/blob/master/layouts/partials/section5.html#L12 so the form has the action and setup required. For example:

```
          <form action="https://formspree.io/f/YOUR FORM ID" method="POST">
            <div class="columns is-multiline">
              <div class="column is-6">
                <input class="input is-medium" type="text" placeholder="Enter your name" name="name">
              </div>
              <div class="column is-6">
                <input class="input is-medium" type="email" placeholder="Enter your email address" name="email">
              </div>
              <div class="column is-12">
                <textarea class="textarea" rows="10" placeholder="Write something..." name="message"></textarea>
              </div>
              <div class="form-footer has-text-centered mt-10">
                <button class="button cta is-large primary-btn raised is-clear" type="submit">Send Message</button>
              </div>
            </div>
          </form>
```

Hope that helps.  

Would be useful to have that be autowired via the confg.yaml. Hope to make a PR for that.

**Comment by StefMa** [comment]
I guess this is already handled in https://github.com/StefMa/hugo-fresh/pull/141 🙂
