### ISSUE TITLE
How to override CSS?

### ISSUE THREAD

**Issue by aabouzaid** [StefMa/hugo-fresh#186]
Thanks for the clean work, totally love it :clap: 

However, it's not clear to me how to override the CSS of the theme.

**Comment by StefMa** [comment]
Hey @aabouzaid 

since we ship the underlaying CSS as a **hugo module** you should add the theme as git submodules instead.
Checkout [this comment](https://github.com/StefMa/hugo-fresh/issues/175#issuecomment-1858885456) and [the following](https://github.com/StefMa/hugo-fresh/issues/175#issuecomment-1863358700) [two comments](https://github.com/StefMa/hugo-fresh/issues/175#issuecomment-1863967740).

Let me know if this works for you.
We might can add this to our docs if so 🙃

**Comment by aabouzaid** [comment]
@StefMa Thanks for the info.
Probably one line referring to that would be super helpful :+1:

**Comment by StefMa** [comment]
Added to the docs via #191
