### ISSUE TITLE
Including additional single pages does not work

### ISSUE THREAD

**Issue by Feliix42** [StefMa/hugo-fresh#70]
A recent update to Hugo or this theme seems to have broken the "single page" functionality.

I tried to build the example site as well as my own site where I also have a GDPR page linked from the landing page and in both cases, the generated HTML for the single pages is faulty and a mere copy of the landing page. Clicking a link pointing to the subpage in the live preview also does not seem to work as it keeps pointing me to the index page.

I am using the latest version of this theme. As for my Hugo version:
```
[felix@Samaritan] $ hugo version
Hugo Static Site Generator v0.57.2/extended darwin/amd64 BuildDate: unknown
```

**Comment by StefMa** [comment]
Thanks for raising this up. I noticed it as well... Sometimes ☺.

Maybe just try to build it again?

**Comment by lianos** [comment]
FWIW, this is also broken in the same way for me (my hugo version also matches the OP's).

It's also hosed in the same way up on the example site:

https://hugo-fresh.now.sh/blog/first

It's a really clean/neat theme, though ... thank you for your work on this!

**Comment by sureshkvl** [comment]
I am also suffering with this bug.  Thanks for fixing this.

More information:
I downgraded my hugo version to v0.55.6. It works in this.

So looks like recent hugo version  causing this issue.

**Comment by lianos** [comment]
Nice sleuthing @sureshkvl! I can also confirm that this works in hugo v0.55.6

Although it's a bit tangential to this package itself, here are the details on how I downgraded my local hugo install on macOS (using [homebrew](https://brew.sh)) to 0.55.6 so that things can work locally until this theme is fixed to work on the latest hugo version.

I basically followed the instructions outlined in this [stackoverflow answer](https://stackoverflow.com/a/17757092/83761):

First I unlinked the my current hugo install:

```
$ cd /usr/local
$ brew unlink hugo
```

Then, by looking through the [commit history of the hugo homebrew formula](https://github.com/Homebrew/homebrew-core/commits/master/Formula/hugo.rb), I found the commit that corresponds to hugo version 0.55.6 bottle.

I `brew install`-ed and switched to it:

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7185a2f68f0edee588dc810b4d46c7866ec2419b/Formula/hugo.rb
$ brew switch hugo 0.55.6
```

This theme now seems to work and compile single pages using this hugo version ... hope that helps.

**Comment by StefMa** [comment]
Is there any warning or error in your logs while building? Maybe this could
give us a hint what's wrong...

**Comment by souvou** [comment]
Same problem here, using last version of hugo.

Perhaps the warnings of hugo v0.55.6 are relevant?
```WARN 2019/09/07 19:51:43 Page's .Dir is deprecated and will be removed in a future release. Use .File.Dir.```
```WARN 2019/09/07 19:51:43 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.```

**Comment by Feliix42** [comment]
I get two warnings:
```
WARN 2019/09/12 00:41:21 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/09/12 00:41:21 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```
I have two single pages in the project, so this could be either connected or coincidental.

**Comment by nathanbiller** [comment]
I get the same 2 errors as @Feliix42 but only have one static page, so I'm guessing the fact that there's 2 is not connected to the count.

I don't receive any other errors but notice that the index.html underneath the directory for my content is an exact replica of the main index.html file in the root directory of the public folder.

**Comment by nathanbiller** [comment]
I've taken care of the warnings that @souvou mentioned, but that still didn't solve the issue. I believe that something that happened here broke the functionality, but I'm not sure what yet: https://github.com/gohugoio/hugo/milestone/90?closed=1 Open to any ideas; I'd really like to get this working, so I can continue developing my site. :)

**Comment by StefMa** [comment]
Maybe the problem is somewhere that the single pages aren't inside the content/post directory?
Maybe [this](https://gohugo.io/getting-started/directory-structure/) will help us here?!

**Comment by souvou** [comment]
Hi all, the issue is on the following files and the way that block "main" is handled:
- layouts/_default/baseof.html
- layouts/index.html

In particular, 
- baseof.html should only mention the parts that are common in all pages; partials hero, section1, section2, etc should not be included in the main block (i.e., the should be removed because now they get in every page rendered). 
- index.html should include the partials that should be visible in the home page, i.e., hero, section1, section2, etc (instead of being empty)

Hope this helps :)

**Comment by nathanbiller** [comment]
Thanks for the guidance @souvou I was able to make those changes and it's now working for me again on v 0.58.2 :)

I also tweaked the single page to allow including the footer on single pages which is something I think I remembered @StefMa mentioning he'd like at some point. If you include this on your front matter the footer will appear:

`include_footer: true`
